version: 2

sources:
  - name: Shopdb
    database: Shopdb
    schema: public
    tables:
      - name: customer
      - name: orderitem
      - name: orders
      - name: product
      - name: productcategory
